export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST'
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS'
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL'
export const ADDRESS_LIST_RESET = 'ADDRESS_LIST_RESET'

export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST'
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS'
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL'
export const ADDRESS_DETAILS_RESET = 'ADDRESS_DETAILS_RESET'

export const ADDRESS_CREATE_REQUEST = 'ADDRESS_CREATE_REQUEST'
export const ADDRESS_CREATE_SUCCESS = 'ADDRESS_CREATE_SUCCESS'
export const ADDRESS_CREATE_FAIL = 'ADDRESS_CREATE_FAIL'
export const ADDRESS_CREATE_RESET = 'ADDRESS_CREATE_RESET'

export const ADDRESS_REMOVE_REQUEST = 'ADDRESS_REMOVE_REQUEST'
export const ADDRESS_REMOVE_SUCCESS = 'ADDRESS_REMOVE_SUCCESS'
export const ADDRESS_REMOVE_FAIL = 'ADDRESS_REMOVE_FAIL'
export const ADDRESS_REMOVE_RESET = 'ADDRESS_REMOVE_RESET'

export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST'
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS'
export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL'
export const ADDRESS_UPDATE_RESET = 'ADDRESS_UPDATE_RESET'
