export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST'
export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS'
export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL'
export const CART_DETAILS_RESET = 'CART_DETAILS_RESET'

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'
export const CART_ADD_ITEM_RESET = 'CART_ADD_ITEM_RESET'

export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST'
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS'
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL'
export const CART_REMOVE_ITEM_RESET = 'CART_REMOVE_ITEM_RESET'

export const CART_SET_SHIPPING_ADDRESS_REQUEST =
  'CART_SET_SHIPPING_ADDRESS_REQUEST'
export const CART_SET_SHIPPING_ADDRESS_SUCCESS =
  'CART_SET_SHIPPING_ADDRESS_SUCCESS'
export const CART_SET_SHIPPING_ADDRESS_FAIL = 'CART_SET_SHIPPING_ADDRESS_FAIL'
export const CART_SET_SHIPPING_ADDRESS_RESET = 'CART_SET_SHIPPING_ADDRESS_RESET'
